[project]
name = "fst-misc-optimisation"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
   "jupyter-book>=2.0.0b1",
   "numpy>=2.3.1",
]
